name: Deploy Webpack build

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Build Webpack page
        run: |
          npm install
          npm run build

      - name: Render PDF of page
        run: |
          mkdir _site
          npm install chromium
          CHROME_PATH="$(pwd)/node_modules/chromium/lib/chromium/chrome-linux/chrome"
          echo ------------------
          pwd
          echo ------------------
          $CHROME_PATH \
            --headless \
            --no-sandbox \
            --disable-gpu \
            --disable-web-security \
            --run-all-compositor-stages-before-draw \
            --virtual-time-budget=5000 \
            --font-render-hinting=none \
            --print-to-pdf=_site/thesis.pdf \
            file://$(pwd)/dist/index.html
          chmod +r _site/thesis.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
